CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE tenants (
    "Id" uuid NOT NULL,
    "Name" character varying(150) NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_tenants" PRIMARY KEY ("Id")
);

CREATE TABLE audit_logs (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TenantId" uuid,
    "TableName" character varying(100) NOT NULL,
    "RecordId" integer NOT NULL,
    "DeletedData" jsonb NOT NULL,
    "DeletedAt" timestamp without time zone,
    CONSTRAINT "PK_audit_logs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_audit_logs_tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES tenants ("Id") ON DELETE CASCADE
);

CREATE TABLE users (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TenantId" uuid,
    "Email" character varying(100) NOT NULL,
    "PasswordHash" text NOT NULL,
    "PasswordSalt" text NOT NULL,
    "Role" character varying(50) NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_users" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_users_role" CHECK ("Role" IN ('Owner','Manager','User','SuperAdmin','Admin')),
    CONSTRAINT "FK_users_tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES tenants ("Id") ON DELETE SET NULL
);

CREATE TABLE notifications (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Message" text NOT NULL,
    "IsRead" boolean NOT NULL DEFAULT FALSE,
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_notifications" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_notifications_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
);

CREATE TABLE restaurants (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TenantId" uuid NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Location" character varying(255) NOT NULL,
    "OwnerId" integer,
    "ManagerId" integer,
    CONSTRAINT "PK_restaurants" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_restaurants_tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES tenants ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_restaurants_users_ManagerId" FOREIGN KEY ("ManagerId") REFERENCES users ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_restaurants_users_OwnerId" FOREIGN KEY ("OwnerId") REFERENCES users ("Id") ON DELETE SET NULL
);

CREATE TABLE inventory (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RestaurantId" integer NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_inventory" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_inventory_restaurants_RestaurantId" FOREIGN KEY ("RestaurantId") REFERENCES restaurants ("Id") ON DELETE CASCADE
);

CREATE TABLE menu_of_restaurant (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RestaurantId" integer NOT NULL,
    "Name" character varying(100) NOT NULL,
    CONSTRAINT "PK_menu_of_restaurant" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_menu_of_restaurant_restaurants_RestaurantId" FOREIGN KEY ("RestaurantId") REFERENCES restaurants ("Id") ON DELETE CASCADE
);

CREATE TABLE reports (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Type" character varying(50) NOT NULL,
    "RestaurantId" integer NOT NULL,
    "Message" character varying(1000) NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_reports" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_reports_restaurants_RestaurantId" FOREIGN KEY ("RestaurantId") REFERENCES restaurants ("Id") ON DELETE CASCADE
);

CREATE TABLE reviews (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer,
    "RestaurantId" integer NOT NULL,
    "Rating" integer NOT NULL,
    "Comment" character varying(1000),
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_reviews" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_reviews_rating" CHECK ("Rating" >= 1 AND "Rating" <= 5),
    CONSTRAINT "FK_reviews_restaurants_RestaurantId" FOREIGN KEY ("RestaurantId") REFERENCES restaurants ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_reviews_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE SET NULL
);

CREATE TABLE staff (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "RestaurantId" integer NOT NULL,
    "Position" character varying(50) NOT NULL,
    CONSTRAINT "PK_staff" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_staff_restaurants_RestaurantId" FOREIGN KEY ("RestaurantId") REFERENCES restaurants ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_staff_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
);

CREATE TABLE suppliers (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RestaurantId" integer NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Contact" character varying(100),
    CONSTRAINT "PK_suppliers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_suppliers_restaurants_RestaurantId" FOREIGN KEY ("RestaurantId") REFERENCES restaurants ("Id") ON DELETE CASCADE
);

CREATE TABLE menu_items (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "MenuId" integer NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Price" numeric(10,2) NOT NULL,
    "Description" text,
    "CookingTime" integer NOT NULL,
    CONSTRAINT "PK_menu_items" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_menu_items_cooking_time" CHECK ("CookingTime" >= 0),
    CONSTRAINT "CK_menu_items_price" CHECK ("Price" >= 0),
    CONSTRAINT "FK_menu_items_menu_of_restaurant_MenuId" FOREIGN KEY ("MenuId") REFERENCES menu_of_restaurant ("Id") ON DELETE CASCADE
);

CREATE TABLE shifts (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "StaffId" integer NOT NULL,
    "StartTime" timestamp without time zone NOT NULL,
    "EndTime" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_shifts" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_shifts_time" CHECK ("EndTime" > "StartTime"),
    CONSTRAINT "FK_shifts_staff_StaffId" FOREIGN KEY ("StaffId") REFERENCES staff ("Id") ON DELETE CASCADE
);

CREATE TABLE tables (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RestaurantId" integer NOT NULL,
    "Number" integer NOT NULL,
    "Capacity" integer NOT NULL,
    "Status" character varying(50) NOT NULL,
    "AssignedStaffId" integer,
    CONSTRAINT "PK_tables" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_tables_capacity" CHECK ("Capacity" > 0),
    CONSTRAINT "FK_tables_restaurants_RestaurantId" FOREIGN KEY ("RestaurantId") REFERENCES restaurants ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_tables_staff_AssignedStaffId" FOREIGN KEY ("AssignedStaffId") REFERENCES staff ("Id") ON DELETE SET NULL
);

CREATE TABLE inventory_items (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "InventoryId" integer NOT NULL,
    "ItemName" character varying(100) NOT NULL,
    "Quantity" numeric(10,2) NOT NULL,
    "SupplierId" integer,
    "UnitPrice" numeric(10,2) NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_inventory_items" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_inventory_items_quantity" CHECK ("Quantity" >= 0),
    CONSTRAINT "CK_inventory_items_unit_price" CHECK ("UnitPrice" >= 0),
    CONSTRAINT "FK_inventory_items_inventory_InventoryId" FOREIGN KEY ("InventoryId") REFERENCES inventory ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_inventory_items_suppliers_SupplierId" FOREIGN KEY ("SupplierId") REFERENCES suppliers ("Id") ON DELETE SET NULL
);

CREATE TABLE purchase_orders (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RestaurantId" integer NOT NULL,
    "SupplierId" integer NOT NULL,
    "Total" numeric(10,2) NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_purchase_orders" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_purchase_orders_total" CHECK ("Total" >= 0),
    CONSTRAINT "FK_purchase_orders_restaurants_RestaurantId" FOREIGN KEY ("RestaurantId") REFERENCES restaurants ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_purchase_orders_suppliers_SupplierId" FOREIGN KEY ("SupplierId") REFERENCES suppliers ("Id") ON DELETE RESTRICT
);

CREATE TABLE orders (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TableId" integer NOT NULL,
    "Status" character varying(50) NOT NULL,
    "Total" numeric(10,2) NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_orders" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_orders_total" CHECK ("Total" >= 0),
    CONSTRAINT "FK_orders_tables_TableId" FOREIGN KEY ("TableId") REFERENCES tables ("Id") ON DELETE CASCADE
);

CREATE TABLE reservations (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TableId" integer NOT NULL,
    "ReservationDate" date NOT NULL,
    "ReservationTime" time without time zone NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Phone" text,
    "Status" character varying(50) NOT NULL,
    CONSTRAINT "PK_reservations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_reservations_tables_TableId" FOREIGN KEY ("TableId") REFERENCES tables ("Id") ON DELETE CASCADE
);

CREATE TABLE kitchen_queue (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrderId" integer NOT NULL,
    "UpdatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_kitchen_queue" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_kitchen_queue_orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES orders ("Id") ON DELETE CASCADE
);

CREATE TABLE order_items (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrderId" integer NOT NULL,
    "MenuItemId" integer NOT NULL,
    "Quantity" integer NOT NULL,
    "Price" numeric(10,2) NOT NULL,
    CONSTRAINT "PK_order_items" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_order_items_price" CHECK ("Price" >= 0),
    CONSTRAINT "CK_order_items_quantity" CHECK ("Quantity" > 0),
    CONSTRAINT "FK_order_items_menu_items_MenuItemId" FOREIGN KEY ("MenuItemId") REFERENCES menu_items ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_order_items_orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES orders ("Id") ON DELETE CASCADE
);

CREATE TABLE payments (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrderId" integer NOT NULL,
    "Amount" numeric(10,2) NOT NULL,
    "Method" character varying(50) NOT NULL,
    "Status" character varying(50) NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_payments" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_payments_amount" CHECK ("Amount" >= 0),
    CONSTRAINT "FK_payments_orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES orders ("Id") ON DELETE CASCADE
);

CREATE INDEX idx_audit_logs_record_id ON audit_logs ("RecordId");

CREATE INDEX idx_audit_logs_table_name ON audit_logs ("TableName");

CREATE INDEX idx_audit_logs_tenant_id ON audit_logs ("TenantId");

CREATE INDEX idx_inventory_restaurant_id ON inventory ("RestaurantId");

CREATE INDEX idx_inventory_items_inventory_id ON inventory_items ("InventoryId");

CREATE INDEX idx_inventory_items_supplier_id ON inventory_items ("SupplierId");

CREATE INDEX idx_kitchen_queue_order_id ON kitchen_queue ("OrderId");

CREATE INDEX idx_menu_items_menu_id ON menu_items ("MenuId");

CREATE INDEX idx_menu_restaurant_id ON menu_of_restaurant ("RestaurantId");

CREATE UNIQUE INDEX uq_menu_restaurant_name ON menu_of_restaurant ("RestaurantId", "Name");

CREATE INDEX idx_notifications_user_id ON notifications ("UserId");

CREATE INDEX idx_order_items_menu_item_id ON order_items ("MenuItemId");

CREATE INDEX idx_order_items_order_id ON order_items ("OrderId");

CREATE INDEX idx_orders_table_id ON orders ("TableId");

CREATE INDEX idx_payments_order_id ON payments ("OrderId");

CREATE INDEX idx_purchase_orders_supplier_id ON purchase_orders ("SupplierId");

CREATE INDEX "IX_purchase_orders_RestaurantId" ON purchase_orders ("RestaurantId");

CREATE INDEX "IX_reports_RestaurantId" ON reports ("RestaurantId");

CREATE INDEX idx_reservations_table_id ON reservations ("TableId");

CREATE UNIQUE INDEX uq_table_reservation_time ON reservations ("TableId", "ReservationDate", "ReservationTime");

CREATE INDEX idx_restaurants_tenant_id ON restaurants ("TenantId");

CREATE INDEX "IX_restaurants_ManagerId" ON restaurants ("ManagerId");

CREATE INDEX "IX_restaurants_OwnerId" ON restaurants ("OwnerId");

CREATE UNIQUE INDEX uq_tenant_restaurant_name ON restaurants ("TenantId", "Name");

CREATE INDEX idx_reviews_restaurant_id ON reviews ("RestaurantId");

CREATE UNIQUE INDEX "IX_reviews_RestaurantId_UserId" ON reviews ("RestaurantId", "UserId");

CREATE INDEX "IX_reviews_UserId" ON reviews ("UserId");

CREATE INDEX idx_shifts_staff_id ON shifts ("StaffId");

CREATE INDEX idx_staff_restaurant_id ON staff ("RestaurantId");

CREATE UNIQUE INDEX uq_staff_user_restaurant ON staff ("UserId", "RestaurantId");

CREATE INDEX idx_suppliers_restaurant_id ON suppliers ("RestaurantId");

CREATE UNIQUE INDEX uq_supplier_restaurant_name ON suppliers ("RestaurantId", "Name");

CREATE INDEX idx_tables_restaurant_id ON tables ("RestaurantId");

CREATE INDEX "IX_tables_AssignedStaffId" ON tables ("AssignedStaffId");

CREATE UNIQUE INDEX uq_tables_restaurant_number ON tables ("RestaurantId", "Number");

CREATE INDEX idx_users_tenant_id ON users ("TenantId");

CREATE UNIQUE INDEX users_email_key ON users ("Email");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260422194432_InitialCreate', '10.0.7');

COMMIT;

START TRANSACTION;
ALTER TABLE restaurants ENABLE ROW LEVEL SECURITY;

ALTER TABLE restaurants FORCE ROW LEVEL SECURITY;

ALTER TABLE users ENABLE ROW LEVEL SECURITY;

ALTER TABLE users FORCE ROW LEVEL SECURITY;

ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;

ALTER TABLE audit_logs FORCE ROW LEVEL SECURITY;

ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

ALTER TABLE orders FORCE ROW LEVEL SECURITY;

ALTER TABLE tables ENABLE ROW LEVEL SECURITY;

ALTER TABLE tables FORCE ROW LEVEL SECURITY;

ALTER TABLE inventory ENABLE ROW LEVEL SECURITY;

ALTER TABLE inventory FORCE ROW LEVEL SECURITY;

ALTER TABLE inventory_items ENABLE ROW LEVEL SECURITY;

ALTER TABLE inventory_items FORCE ROW LEVEL SECURITY;

ALTER TABLE menu_of_restaurant ENABLE ROW LEVEL SECURITY;

ALTER TABLE menu_of_restaurant FORCE ROW LEVEL SECURITY;

ALTER TABLE menu_items ENABLE ROW LEVEL SECURITY;

ALTER TABLE menu_items FORCE ROW LEVEL SECURITY;

ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;

ALTER TABLE order_items FORCE ROW LEVEL SECURITY;

ALTER TABLE kitchen_queue ENABLE ROW LEVEL SECURITY;

ALTER TABLE kitchen_queue FORCE ROW LEVEL SECURITY;

ALTER TABLE payments ENABLE ROW LEVEL SECURITY;

ALTER TABLE payments FORCE ROW LEVEL SECURITY;

ALTER TABLE purchase_orders ENABLE ROW LEVEL SECURITY;

ALTER TABLE purchase_orders FORCE ROW LEVEL SECURITY;

ALTER TABLE reservations ENABLE ROW LEVEL SECURITY;

ALTER TABLE reservations FORCE ROW LEVEL SECURITY;

ALTER TABLE staff ENABLE ROW LEVEL SECURITY;

ALTER TABLE staff FORCE ROW LEVEL SECURITY;

ALTER TABLE shifts ENABLE ROW LEVEL SECURITY;

ALTER TABLE shifts FORCE ROW LEVEL SECURITY;

ALTER TABLE suppliers ENABLE ROW LEVEL SECURITY;

ALTER TABLE suppliers FORCE ROW LEVEL SECURITY;

ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

ALTER TABLE notifications FORCE ROW LEVEL SECURITY;

ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;

ALTER TABLE reviews FORCE ROW LEVEL SECURITY;

ALTER TABLE reports ENABLE ROW LEVEL SECURITY;

ALTER TABLE reports FORCE ROW LEVEL SECURITY;

    CREATE POLICY tenant_isolation ON restaurants
    USING ("TenantId" = current_setting('app.current_tenant_id', true)::uuid);

    CREATE POLICY tenant_isolation ON users
    USING ("TenantId" = current_setting('app.current_tenant_id', true)::uuid);

    CREATE POLICY tenant_isolation ON audit_logs
    USING ("TenantId" = current_setting('app.current_tenant_id', true)::uuid);

    CREATE POLICY tenant_isolation ON tables
    USING (
        "RestaurantId" IN (
            SELECT "Id" FROM restaurants
            WHERE "TenantId" = current_setting('app.current_tenant_id', true)::uuid
        )
    );

    CREATE POLICY tenant_isolation ON menu_of_restaurant
    USING (
        "RestaurantId" IN (
            SELECT "Id" FROM restaurants
            WHERE "TenantId" = current_setting('app.current_tenant_id', true)::uuid
        )
    );

    CREATE POLICY tenant_isolation ON inventory
    USING (
        "RestaurantId" IN (
            SELECT "Id" FROM restaurants
            WHERE "TenantId" = current_setting('app.current_tenant_id', true)::uuid
        )
    );

    CREATE POLICY tenant_isolation ON suppliers
    USING (
        "RestaurantId" IN (
            SELECT "Id" FROM restaurants
            WHERE "TenantId" = current_setting('app.current_tenant_id', true)::uuid
        )
    );

    CREATE POLICY tenant_isolation ON purchase_orders
    USING (
        "RestaurantId" IN (
            SELECT "Id" FROM restaurants
            WHERE "TenantId" = current_setting('app.current_tenant_id', true)::uuid
        )
    );

    CREATE POLICY tenant_isolation ON reports
    USING (
        "RestaurantId" IN (
            SELECT "Id" FROM restaurants
            WHERE "TenantId" = current_setting('app.current_tenant_id', true)::uuid
        )
    );

    CREATE POLICY tenant_isolation ON reviews
    USING (
        "RestaurantId" IN (
            SELECT "Id" FROM restaurants
            WHERE "TenantId" = current_setting('app.current_tenant_id', true)::uuid
        )
    );

    CREATE POLICY tenant_isolation ON staff
    USING (
        "RestaurantId" IN (
            SELECT "Id" FROM restaurants
            WHERE "TenantId" = current_setting('app.current_tenant_id', true)::uuid
        )
    );

    CREATE POLICY tenant_isolation ON orders
    USING (
        "TableId" IN (
            SELECT t."Id" FROM tables t
            JOIN restaurants r ON r."Id" = t."RestaurantId"
            WHERE r."TenantId" = current_setting('app.current_tenant_id', true)::uuid
        )
    );

    CREATE POLICY tenant_isolation ON reservations
    USING (
        "TableId" IN (
            SELECT t."Id" FROM tables t
            JOIN restaurants r ON r."Id" = t."RestaurantId"
            WHERE r."TenantId" = current_setting('app.current_tenant_id', true)::uuid
        )
    );

    CREATE POLICY tenant_isolation ON menu_items
    USING (
        "MenuId" IN (
            SELECT m."Id" FROM menu_of_restaurant m
            JOIN restaurants r ON r."Id" = m."RestaurantId"
            WHERE r."TenantId" = current_setting('app.current_tenant_id', true)::uuid
        )
    );

    CREATE POLICY tenant_isolation ON inventory_items
    USING (
        "InventoryId" IN (
            SELECT i."Id" FROM inventory i
            JOIN restaurants r ON r."Id" = i."RestaurantId"
            WHERE r."TenantId" = current_setting('app.current_tenant_id', true)::uuid
        )
    );

    CREATE POLICY tenant_isolation ON order_items
    USING (
        "OrderId" IN (
            SELECT o."Id" FROM orders o
            JOIN tables t ON t."Id" = o."TableId"
            JOIN restaurants r ON r."Id" = t."RestaurantId"
            WHERE r."TenantId" = current_setting('app.current_tenant_id', true)::uuid
        )
    );

    CREATE POLICY tenant_isolation ON kitchen_queue
    USING (
        "OrderId" IN (
            SELECT o."Id" FROM orders o
            JOIN tables t ON t."Id" = o."TableId"
            JOIN restaurants r ON r."Id" = t."RestaurantId"
            WHERE r."TenantId" = current_setting('app.current_tenant_id', true)::uuid
        )
    );

    CREATE POLICY tenant_isolation ON payments
    USING (
        "OrderId" IN (
            SELECT o."Id" FROM orders o
            JOIN tables t ON t."Id" = o."TableId"
            JOIN restaurants r ON r."Id" = t."RestaurantId"
            WHERE r."TenantId" = current_setting('app.current_tenant_id', true)::uuid
        )
    );

    CREATE POLICY tenant_isolation ON shifts
    USING (
        "StaffId" IN (
            SELECT s."Id" FROM staff s
            JOIN restaurants r ON r."Id" = s."RestaurantId"
            WHERE r."TenantId" = current_setting('app.current_tenant_id', true)::uuid
        )
    );

    CREATE POLICY tenant_isolation ON notifications
    USING (
        "UserId" IN (
            SELECT "Id" FROM users
            WHERE "TenantId" = current_setting('app.current_tenant_id', true)::uuid
        )
    );

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260425231905_EnableRowLevelSecurity', '10.0.7');

COMMIT;

START TRANSACTION;
ALTER TABLE users DROP COLUMN "PasswordHash";

ALTER TABLE users DROP COLUMN "PasswordSalt";

ALTER TABLE users ADD "SupabaseUserId" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';

CREATE UNIQUE INDEX users_supabase_id_key ON users ("SupabaseUserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260426125335_UseSupabaseUsers', '10.0.7');

COMMIT;

START TRANSACTION;
ALTER TABLE users ALTER COLUMN "CreatedAt" TYPE timestamp with time zone;

ALTER TABLE tenants ALTER COLUMN "CreatedAt" TYPE timestamp with time zone;

ALTER TABLE shifts ALTER COLUMN "StartTime" TYPE timestamp with time zone;

ALTER TABLE shifts ALTER COLUMN "EndTime" TYPE timestamp with time zone;

ALTER TABLE reviews ALTER COLUMN "CreatedAt" TYPE timestamp with time zone;

ALTER TABLE reports ALTER COLUMN "CreatedAt" TYPE timestamp with time zone;

ALTER TABLE purchase_orders ALTER COLUMN "CreatedAt" TYPE timestamp with time zone;

ALTER TABLE payments ALTER COLUMN "CreatedAt" TYPE timestamp with time zone;

ALTER TABLE orders ALTER COLUMN "CreatedAt" TYPE timestamp with time zone;

ALTER TABLE notifications ALTER COLUMN "CreatedAt" TYPE timestamp with time zone;

ALTER TABLE kitchen_queue ALTER COLUMN "UpdatedAt" TYPE timestamp with time zone;

ALTER TABLE inventory_items ALTER COLUMN "CreatedAt" TYPE timestamp with time zone;

ALTER TABLE inventory ALTER COLUMN "CreatedAt" TYPE timestamp with time zone;

ALTER TABLE audit_logs ALTER COLUMN "DeletedAt" TYPE timestamp with time zone;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260426175041_UseTimestampWithTimeZone', '10.0.7');

COMMIT;

START TRANSACTION;
do $$
begin
    if not exists (select 1 from pg_roles where rolname = 'app_authenticated') then
        create role app_authenticated;
    end if;

    execute format('grant app_authenticated to %I', current_user);
end
$$;

grant usage on schema public to app_authenticated;
grant select, insert, update, delete on all tables in schema public to app_authenticated;
grant usage, select on all sequences in schema public to app_authenticated;

do $$
declare
    policy_record record;
begin
    for policy_record in
        select schemaname, tablename, policyname
        from pg_policies
        where schemaname = 'public'
          and tablename in (
              'tenants', 'restaurants', 'users', 'audit_logs', 'orders', 'tables',
              'inventory', 'inventory_items', 'menu_of_restaurant', 'menu_items',
              'order_items', 'kitchen_queue', 'payments', 'purchase_orders',
              'reservations', 'staff', 'shifts', 'suppliers', 'notifications',
              'reviews', 'reports'
          )
    loop
        execute format(
            'drop policy if exists %I on %I.%I',
            policy_record.policyname,
            policy_record.schemaname,
            policy_record.tablename
        );
    end loop;
end
$$;

alter table tenants enable row level security;
alter table tenants force row level security;

alter table restaurants enable row level security;
alter table restaurants force row level security;

alter table users enable row level security;
alter table users force row level security;

alter table audit_logs enable row level security;
alter table audit_logs force row level security;

alter table orders enable row level security;
alter table orders force row level security;

alter table tables enable row level security;
alter table tables force row level security;

alter table inventory enable row level security;
alter table inventory force row level security;

alter table inventory_items enable row level security;
alter table inventory_items force row level security;

alter table menu_of_restaurant enable row level security;
alter table menu_of_restaurant force row level security;

alter table menu_items enable row level security;
alter table menu_items force row level security;

alter table order_items enable row level security;
alter table order_items force row level security;

alter table kitchen_queue enable row level security;
alter table kitchen_queue force row level security;

alter table payments enable row level security;
alter table payments force row level security;

alter table purchase_orders enable row level security;
alter table purchase_orders force row level security;

alter table reservations enable row level security;
alter table reservations force row level security;

alter table staff enable row level security;
alter table staff force row level security;

alter table shifts enable row level security;
alter table shifts force row level security;

alter table suppliers enable row level security;
alter table suppliers force row level security;

alter table notifications enable row level security;
alter table notifications force row level security;

alter table reviews enable row level security;
alter table reviews force row level security;

alter table reports enable row level security;
alter table reports force row level security;

create policy app_tenant_rls on tenants
for all
to app_authenticated
using (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
or "Id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
)
with check (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
or "Id" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
);

create policy app_tenant_rls on restaurants
for all
to app_authenticated
using (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
or "TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
)
with check (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
or "TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
);

create policy app_tenant_rls on users
for all
to app_authenticated
using (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
or "TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
or "SupabaseUserId" = nullif(current_setting('app.supabase_user_id', true), '')::uuid
)
with check (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
or "TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
or "SupabaseUserId" = nullif(current_setting('app.supabase_user_id', true), '')::uuid
);

create policy app_tenant_rls on audit_logs
for all
to app_authenticated
using (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
or "TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
)
with check (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
or "TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
);

create policy app_tenant_rls on tables
for all
to app_authenticated
using (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
or "RestaurantId" in (
    select r."Id"
    from restaurants r
    where r."TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
)
)
with check (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
or "RestaurantId" in (
    select r."Id"
    from restaurants r
    where r."TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
)
);

create policy app_tenant_rls on menu_of_restaurant
for all
to app_authenticated
using (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
or "RestaurantId" in (
    select r."Id"
    from restaurants r
    where r."TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
)
)
with check (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
or "RestaurantId" in (
    select r."Id"
    from restaurants r
    where r."TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
)
);

create policy app_tenant_rls on inventory
for all
to app_authenticated
using (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
or "RestaurantId" in (
    select r."Id"
    from restaurants r
    where r."TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
)
)
with check (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
or "RestaurantId" in (
    select r."Id"
    from restaurants r
    where r."TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
)
);

create policy app_tenant_rls on suppliers
for all
to app_authenticated
using (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
or "RestaurantId" in (
    select r."Id"
    from restaurants r
    where r."TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
)
)
with check (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
or "RestaurantId" in (
    select r."Id"
    from restaurants r
    where r."TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
)
);

create policy app_tenant_rls on purchase_orders
for all
to app_authenticated
using (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
or "RestaurantId" in (
    select r."Id"
    from restaurants r
    where r."TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
)
)
with check (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
or "RestaurantId" in (
    select r."Id"
    from restaurants r
    where r."TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
)
);

create policy app_tenant_rls on reports
for all
to app_authenticated
using (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
or "RestaurantId" in (
    select r."Id"
    from restaurants r
    where r."TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
)
)
with check (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
or "RestaurantId" in (
    select r."Id"
    from restaurants r
    where r."TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
)
);

create policy app_tenant_rls on reviews
for all
to app_authenticated
using (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
or "RestaurantId" in (
    select r."Id"
    from restaurants r
    where r."TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
)
)
with check (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
or "RestaurantId" in (
    select r."Id"
    from restaurants r
    where r."TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
)
);

create policy app_tenant_rls on staff
for all
to app_authenticated
using (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
or "RestaurantId" in (
    select r."Id"
    from restaurants r
    where r."TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
)
)
with check (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
or "RestaurantId" in (
    select r."Id"
    from restaurants r
    where r."TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
)
);

create policy app_tenant_rls on orders
for all
to app_authenticated
using (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
or "TableId" in (
    select t."Id"
    from tables t
    join restaurants r on r."Id" = t."RestaurantId"
    where r."TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
)
)
with check (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
or "TableId" in (
    select t."Id"
    from tables t
    join restaurants r on r."Id" = t."RestaurantId"
    where r."TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
)
);

create policy app_tenant_rls on reservations
for all
to app_authenticated
using (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
or "TableId" in (
    select t."Id"
    from tables t
    join restaurants r on r."Id" = t."RestaurantId"
    where r."TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
)
)
with check (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
or "TableId" in (
    select t."Id"
    from tables t
    join restaurants r on r."Id" = t."RestaurantId"
    where r."TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
)
);

create policy app_tenant_rls on menu_items
for all
to app_authenticated
using (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
or "MenuId" in (
    select m."Id"
    from menu_of_restaurant m
    join restaurants r on r."Id" = m."RestaurantId"
    where r."TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
)
)
with check (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
or "MenuId" in (
    select m."Id"
    from menu_of_restaurant m
    join restaurants r on r."Id" = m."RestaurantId"
    where r."TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
)
);

create policy app_tenant_rls on inventory_items
for all
to app_authenticated
using (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
or "InventoryId" in (
    select i."Id"
    from inventory i
    join restaurants r on r."Id" = i."RestaurantId"
    where r."TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
)
)
with check (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
or "InventoryId" in (
    select i."Id"
    from inventory i
    join restaurants r on r."Id" = i."RestaurantId"
    where r."TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
)
);

create policy app_tenant_rls on order_items
for all
to app_authenticated
using (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
or "OrderId" in (
    select o."Id"
    from orders o
    join tables t on t."Id" = o."TableId"
    join restaurants r on r."Id" = t."RestaurantId"
    where r."TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
)
)
with check (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
or "OrderId" in (
    select o."Id"
    from orders o
    join tables t on t."Id" = o."TableId"
    join restaurants r on r."Id" = t."RestaurantId"
    where r."TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
)
);

create policy app_tenant_rls on kitchen_queue
for all
to app_authenticated
using (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
or "OrderId" in (
    select o."Id"
    from orders o
    join tables t on t."Id" = o."TableId"
    join restaurants r on r."Id" = t."RestaurantId"
    where r."TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
)
)
with check (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
or "OrderId" in (
    select o."Id"
    from orders o
    join tables t on t."Id" = o."TableId"
    join restaurants r on r."Id" = t."RestaurantId"
    where r."TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
)
);

create policy app_tenant_rls on payments
for all
to app_authenticated
using (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
or "OrderId" in (
    select o."Id"
    from orders o
    join tables t on t."Id" = o."TableId"
    join restaurants r on r."Id" = t."RestaurantId"
    where r."TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
)
)
with check (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
or "OrderId" in (
    select o."Id"
    from orders o
    join tables t on t."Id" = o."TableId"
    join restaurants r on r."Id" = t."RestaurantId"
    where r."TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
)
);

create policy app_tenant_rls on shifts
for all
to app_authenticated
using (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
or "StaffId" in (
    select s."Id"
    from staff s
    join restaurants r on r."Id" = s."RestaurantId"
    where r."TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
)
)
with check (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
or "StaffId" in (
    select s."Id"
    from staff s
    join restaurants r on r."Id" = s."RestaurantId"
    where r."TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
)
);

create policy app_tenant_rls on notifications
for all
to app_authenticated
using (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
or "UserId" = nullif(current_setting('app.user_id', true), '')::integer
or "UserId" in (
    select u."Id"
    from users u
    where u."TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
)
)
with check (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
or "UserId" = nullif(current_setting('app.user_id', true), '')::integer
or "UserId" in (
    select u."Id"
    from users u
    where u."TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
)
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260501210416_ApplyTenantRlsPoliciesForAllTables', '10.0.7');

COMMIT;

START TRANSACTION;
CREATE TABLE table_sessions (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "RestaurantId" integer NOT NULL,
    "TableId" integer NOT NULL,
    "OpenedByUserId" integer NOT NULL,
    "Status" character varying(50) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "ClosedAt" timestamp with time zone,
    "LastSeenAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_table_sessions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_table_sessions_restaurants_RestaurantId" FOREIGN KEY ("RestaurantId") REFERENCES restaurants ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_table_sessions_tables_TableId" FOREIGN KEY ("TableId") REFERENCES tables ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_table_sessions_tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES tenants ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_table_sessions_users_OpenedByUserId" FOREIGN KEY ("OpenedByUserId") REFERENCES users ("Id") ON DELETE RESTRICT
);

CREATE INDEX idx_table_sessions_restaurant_id ON table_sessions ("RestaurantId");

CREATE INDEX idx_table_sessions_table_id ON table_sessions ("TableId");

CREATE INDEX idx_table_sessions_table_status ON table_sessions ("TableId", "Status");

CREATE INDEX idx_table_sessions_tenant_id ON table_sessions ("TenantId");

CREATE INDEX "IX_table_sessions_OpenedByUserId" ON table_sessions ("OpenedByUserId");

grant select, insert, update, delete on table_sessions to app_authenticated;

alter table table_sessions enable row level security;
alter table table_sessions force row level security;

create policy app_tenant_rls on table_sessions
for all
to app_authenticated
using (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
    or "TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
)
with check (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
    or "TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260508130513_AddTableSessions', '10.0.7');

COMMIT;

START TRANSACTION;
ALTER TABLE users DROP CONSTRAINT "CK_users_role";

ALTER TABLE users ADD CONSTRAINT "CK_users_role" CHECK ("Role" IN ('Owner','Manager','User','Table','SuperAdmin','Admin'));

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260508131503_AddTableUserRole', '10.0.7');

COMMIT;

START TRANSACTION;
ALTER TABLE users DROP CONSTRAINT "CK_users_role";

ALTER TABLE orders ADD "DiningSessionId" integer;

ALTER TABLE order_items ADD "Notes" character varying(300);

CREATE TABLE dining_sessions (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TenantId" uuid NOT NULL,
    "RestaurantId" integer NOT NULL,
    "TableId" integer NOT NULL,
    "OpenedByUserId" integer NOT NULL,
    "PartySize" integer NOT NULL,
    "Status" character varying(50) NOT NULL,
    "SeatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "ClosedAt" timestamp with time zone,
    CONSTRAINT "PK_dining_sessions" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_dining_sessions_party_size" CHECK ("PartySize" > 0),
    CONSTRAINT "FK_dining_sessions_restaurants_RestaurantId" FOREIGN KEY ("RestaurantId") REFERENCES restaurants ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_dining_sessions_tables_TableId" FOREIGN KEY ("TableId") REFERENCES tables ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_dining_sessions_tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES tenants ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_dining_sessions_users_OpenedByUserId" FOREIGN KEY ("OpenedByUserId") REFERENCES users ("Id") ON DELETE RESTRICT
);

CREATE TABLE menu_item_filters (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TenantId" uuid NOT NULL,
    "Name" character varying(80) NOT NULL,
    "Slug" character varying(80) NOT NULL,
    "SortOrder" integer NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_menu_item_filters" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_menu_item_filters_tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES tenants ("Id") ON DELETE CASCADE
);

CREATE TABLE menu_item_filter_assignments (
    "MenuItemId" integer NOT NULL,
    "MenuItemFilterId" integer NOT NULL,
    CONSTRAINT "PK_menu_item_filter_assignments" PRIMARY KEY ("MenuItemId", "MenuItemFilterId"),
    CONSTRAINT "FK_menu_item_filter_assignments_menu_item_filters_MenuItemFilt~" FOREIGN KEY ("MenuItemFilterId") REFERENCES menu_item_filters ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_menu_item_filter_assignments_menu_items_MenuItemId" FOREIGN KEY ("MenuItemId") REFERENCES menu_items ("Id") ON DELETE CASCADE
);

ALTER TABLE users ADD CONSTRAINT "CK_users_role" CHECK ("Role" IN ('Owner','Manager','Host','User','Table','SuperAdmin','Admin'));

CREATE INDEX idx_orders_dining_session_id ON orders ("DiningSessionId");

CREATE INDEX idx_dining_sessions_restaurant_id ON dining_sessions ("RestaurantId");

CREATE INDEX idx_dining_sessions_table_id ON dining_sessions ("TableId");

CREATE INDEX idx_dining_sessions_table_status ON dining_sessions ("TableId", "Status");

CREATE INDEX idx_dining_sessions_tenant_id ON dining_sessions ("TenantId");

CREATE INDEX "IX_dining_sessions_OpenedByUserId" ON dining_sessions ("OpenedByUserId");

CREATE INDEX idx_menu_item_filter_assignments_filter_id ON menu_item_filter_assignments ("MenuItemFilterId");

CREATE INDEX idx_menu_item_filters_tenant_id ON menu_item_filters ("TenantId");

CREATE UNIQUE INDEX uq_menu_item_filters_tenant_slug ON menu_item_filters ("TenantId", "Slug");

ALTER TABLE orders ADD CONSTRAINT "FK_orders_dining_sessions_DiningSessionId" FOREIGN KEY ("DiningSessionId") REFERENCES dining_sessions ("Id") ON DELETE SET NULL;

grant select, insert, update, delete on dining_sessions to app_authenticated;
grant usage, select on sequence "dining_sessions_Id_seq" to app_authenticated;

grant select, insert, update, delete on menu_item_filters to app_authenticated;
grant usage, select on sequence "menu_item_filters_Id_seq" to app_authenticated;

grant select, insert, update, delete on menu_item_filter_assignments to app_authenticated;

alter table dining_sessions enable row level security;
alter table dining_sessions force row level security;

create policy app_tenant_rls on dining_sessions
for all
to app_authenticated
using (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
    or "TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
)
with check (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
    or "TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
);

alter table menu_item_filters enable row level security;
alter table menu_item_filters force row level security;

create policy app_tenant_rls on menu_item_filters
for all
to app_authenticated
using (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
    or "TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
)
with check (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
    or "TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
);

alter table menu_item_filter_assignments enable row level security;
alter table menu_item_filter_assignments force row level security;

create policy app_tenant_rls on menu_item_filter_assignments
for all
to app_authenticated
using (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
    or exists (
        select 1
        from menu_items mi
        join menu_of_restaurant m on m."Id" = mi."MenuId"
        join restaurants r on r."Id" = m."RestaurantId"
        where mi."Id" = "MenuItemId"
        and r."TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
    )
)
with check (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
    or exists (
        select 1
        from menu_items mi
        join menu_of_restaurant m on m."Id" = mi."MenuId"
        join restaurants r on r."Id" = m."RestaurantId"
        join menu_item_filters mif on mif."Id" = "MenuItemFilterId"
        where mi."Id" = "MenuItemId"
        and r."TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
        and mif."TenantId" = r."TenantId"
    )
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260508225655_AddDiningSessionsMenuFiltersAndOrderItemNotes', '10.0.7');

COMMIT;

START TRANSACTION;
ALTER TABLE menu_item_filters ADD "RestaurantId" integer;

CREATE INDEX idx_menu_item_filters_restaurant_id ON menu_item_filters ("RestaurantId");

ALTER TABLE menu_item_filters ADD CONSTRAINT "FK_menu_item_filters_restaurants_RestaurantId" FOREIGN KEY ("RestaurantId") REFERENCES restaurants ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260509123506_AddRestaurantScopedMenuFilters', '10.0.7');

COMMIT;

START TRANSACTION;
ALTER TABLE menu_items ADD "ImagePublicId" character varying(255);

ALTER TABLE menu_items ADD "ImageUrl" character varying(500);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260509131517_AddMenuItemCloudinaryImages', '10.0.7');

COMMIT;

START TRANSACTION;
ALTER TABLE restaurants ADD "ContactEmail" character varying(150);

ALTER TABLE restaurants ADD "ContactPhone" character varying(50);

ALTER TABLE restaurants ADD "CuisineType" character varying(100);

ALTER TABLE restaurants ADD "LogoUrl" character varying(500);

CREATE TABLE restaurant_approval_requests (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TenantId" uuid NOT NULL,
    "RequestedByUserId" integer NOT NULL,
    "RestaurantId" integer,
    "Type" character varying(32) NOT NULL,
    "Status" character varying(32) NOT NULL,
    "Summary" character varying(300) NOT NULL,
    "ProtectedPayload" text NOT NULL,
    "AdminPasswordConfirmation" character varying(120),
    "RejectionReason" character varying(500),
    "ReviewedByUserId" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ReviewedAt" timestamp with time zone,
    CONSTRAINT "PK_restaurant_approval_requests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_restaurant_approval_requests_restaurants_RestaurantId" FOREIGN KEY ("RestaurantId") REFERENCES restaurants ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_restaurant_approval_requests_tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES tenants ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_restaurant_approval_requests_users_RequestedByUserId" FOREIGN KEY ("RequestedByUserId") REFERENCES users ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_restaurant_approval_requests_users_ReviewedByUserId" FOREIGN KEY ("ReviewedByUserId") REFERENCES users ("Id") ON DELETE SET NULL
);

CREATE INDEX "IX_restaurant_approval_requests_RequestedByUserId" ON restaurant_approval_requests ("RequestedByUserId");

CREATE INDEX "IX_restaurant_approval_requests_RestaurantId" ON restaurant_approval_requests ("RestaurantId");

CREATE INDEX "IX_restaurant_approval_requests_ReviewedByUserId" ON restaurant_approval_requests ("ReviewedByUserId");

CREATE INDEX "IX_restaurant_approval_requests_TenantId" ON restaurant_approval_requests ("TenantId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260509203040_AddRestaurantApprovalRequests', '10.0.7');

COMMIT;

START TRANSACTION;
ALTER TABLE staff DROP CONSTRAINT "FK_staff_users_UserId";

ALTER TABLE users DROP CONSTRAINT "CK_users_role";

DROP INDEX uq_staff_user_restaurant;

ALTER TABLE users ADD "RestaurantId" integer;

ALTER TABLE staff ADD "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP);

ALTER TABLE staff ADD "CredentialHash" character varying(200) NOT NULL DEFAULT '';

ALTER TABLE staff ADD "FullName" character varying(150) NOT NULL DEFAULT '';

ALTER TABLE staff ADD "IsActive" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE staff ADD "TenantId" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';

ALTER TABLE staff RENAME COLUMN "Position" TO "CredentialType";

ALTER TABLE orders ADD "PosUserId" integer;

ALTER TABLE orders ADD "WaiterStaffId" integer;

CREATE TABLE pos_waiter_sessions (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PosUserId" integer NOT NULL,
    "StaffId" integer NOT NULL,
    "TenantId" uuid NOT NULL,
    "RestaurantId" integer NOT NULL,
    "OpenedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "ExpiresAt" timestamp with time zone,
    "ClosedAt" timestamp with time zone,
    CONSTRAINT "PK_pos_waiter_sessions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_pos_waiter_sessions_restaurants_RestaurantId" FOREIGN KEY ("RestaurantId") REFERENCES restaurants ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_pos_waiter_sessions_staff_StaffId" FOREIGN KEY ("StaffId") REFERENCES staff ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_pos_waiter_sessions_tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES tenants ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_pos_waiter_sessions_users_PosUserId" FOREIGN KEY ("PosUserId") REFERENCES users ("Id") ON DELETE CASCADE
);

UPDATE users AS u
SET "RestaurantId" = s."RestaurantId"
FROM staff AS s
WHERE s."UserId" = u."Id"
  AND u."RestaurantId" IS NULL;

UPDATE users
SET "Role" = 'TableDevice'
WHERE "Role" = 'Table';

UPDATE users
SET "Role" = 'HostDevice'
WHERE "Role" = 'Host';

UPDATE users
SET "Role" = 'PosDevice'
WHERE "Role" = 'User';

UPDATE staff AS s
SET "TenantId" = r."TenantId",
    "FullName" = COALESCE((SELECT u."Email" FROM users AS u WHERE u."Id" = s."UserId"), 'Legacy Waiter #' || s."Id"::text),
    "CredentialHash" = md5('LEGACY-WAITER-' || s."Id"::text),
    "CredentialType" = 'ManualId',
    "IsActive" = FALSE
FROM restaurants AS r
WHERE r."Id" = s."RestaurantId";

ALTER TABLE staff DROP COLUMN "UserId";

CREATE INDEX idx_users_restaurant_id ON users ("RestaurantId");

ALTER TABLE users ADD CONSTRAINT "CK_users_role" CHECK ("Role" IN ('Owner','Manager','Admin','SuperAdmin','PosDevice','TableDevice','KitchenDevice','HostDevice'));

CREATE INDEX idx_staff_tenant_id ON staff ("TenantId");

CREATE UNIQUE INDEX uq_staff_restaurant_credential ON staff ("RestaurantId", "CredentialHash");

CREATE INDEX idx_orders_pos_user_id ON orders ("PosUserId");

CREATE INDEX idx_orders_waiter_staff_id ON orders ("WaiterStaffId");

CREATE INDEX idx_pos_waiter_sessions_pos_user_id ON pos_waiter_sessions ("PosUserId");

CREATE INDEX idx_pos_waiter_sessions_restaurant_id ON pos_waiter_sessions ("RestaurantId");

CREATE INDEX idx_pos_waiter_sessions_staff_id ON pos_waiter_sessions ("StaffId");

CREATE INDEX idx_pos_waiter_sessions_tenant_id ON pos_waiter_sessions ("TenantId");

ALTER TABLE orders ADD CONSTRAINT "FK_orders_staff_WaiterStaffId" FOREIGN KEY ("WaiterStaffId") REFERENCES staff ("Id") ON DELETE SET NULL;

ALTER TABLE orders ADD CONSTRAINT "FK_orders_users_PosUserId" FOREIGN KEY ("PosUserId") REFERENCES users ("Id") ON DELETE SET NULL;

ALTER TABLE staff ADD CONSTRAINT "FK_staff_tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES tenants ("Id") ON DELETE CASCADE;

ALTER TABLE users ADD CONSTRAINT "FK_users_restaurants_RestaurantId" FOREIGN KEY ("RestaurantId") REFERENCES restaurants ("Id") ON DELETE SET NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260509224306_RefactorStaffDeviceAuthModel', '10.0.7');

COMMIT;

START TRANSACTION;
grant select, insert, update, delete on restaurant_approval_requests to app_authenticated;
grant usage, select on sequence "restaurant_approval_requests_Id_seq" to app_authenticated;

grant select, insert, update, delete on pos_waiter_sessions to app_authenticated;
grant usage, select on sequence "pos_waiter_sessions_Id_seq" to app_authenticated;

alter default privileges in schema public grant select, insert, update, delete on tables to app_authenticated;
alter default privileges in schema public grant usage, select on sequences to app_authenticated;

alter table restaurant_approval_requests enable row level security;
alter table restaurant_approval_requests force row level security;
drop policy if exists app_tenant_rls on restaurant_approval_requests;
create policy app_tenant_rls on restaurant_approval_requests
for all
to app_authenticated
using (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
    or "TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
)
with check (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
    or "TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
);

alter table pos_waiter_sessions enable row level security;
alter table pos_waiter_sessions force row level security;
drop policy if exists app_tenant_rls on pos_waiter_sessions;
create policy app_tenant_rls on pos_waiter_sessions
for all
to app_authenticated
using (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
    or "TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
)
with check (
    current_setting('app.current_user_role', true) = 'SuperAdmin'
    or "TenantId" = nullif(current_setting('app.current_tenant_id', true), '')::uuid
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260510131500_GrantRlsForRestaurantApprovalRequestsAndPosWaiterSessions', '10.0.7');

COMMIT;

START TRANSACTION;
ALTER TABLE users ADD "IsActivated" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE users DROP CONSTRAINT IF EXISTS "CK_users_role";
ALTER TABLE users ADD CONSTRAINT "CK_users_role"
CHECK ("Role" IN ('Pending','Owner','Manager','Admin','SuperAdmin','PosDevice','TableDevice','KitchenDevice','HostDevice'));

UPDATE users
SET "IsActivated" = CASE
    WHEN "Role" = 'SuperAdmin' THEN TRUE
    WHEN "Role" IN ('Owner', 'Admin') AND "TenantId" IS NOT NULL THEN TRUE
    WHEN "Role" IN ('Manager', 'PosDevice', 'TableDevice', 'KitchenDevice', 'HostDevice')
        AND "TenantId" IS NOT NULL
        AND "RestaurantId" IS NOT NULL THEN TRUE
    ELSE FALSE
END;

UPDATE users
SET "RestaurantId" = NULL
WHERE "Role" = 'Owner';

UPDATE users u
SET "RestaurantId" = r."Id"
FROM restaurants r
WHERE u."Id" = r."ManagerId"
  AND u."Role" = 'Manager';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260510170000_AddPendingUserActivation', '10.0.7');

COMMIT;

START TRANSACTION;
ALTER TABLE users
ADD COLUMN IF NOT EXISTS "IsActivated" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE users DROP CONSTRAINT IF EXISTS "CK_users_role";
ALTER TABLE users ADD CONSTRAINT "CK_users_role"
CHECK ("Role" IN ('Pending','Owner','Manager','Admin','SuperAdmin','PosDevice','TableDevice','KitchenDevice','HostDevice'));

UPDATE users
SET "IsActivated" = CASE
    WHEN "Role" = 'SuperAdmin' THEN TRUE
    WHEN "Role" IN ('Owner', 'Admin') AND "TenantId" IS NOT NULL THEN TRUE
    WHEN "Role" IN ('Manager', 'PosDevice', 'TableDevice', 'KitchenDevice', 'HostDevice')
        AND "TenantId" IS NOT NULL
        AND "RestaurantId" IS NOT NULL THEN TRUE
    ELSE FALSE
END;

UPDATE users
SET "RestaurantId" = NULL
WHERE "Role" = 'Owner';

UPDATE users u
SET "RestaurantId" = r."Id"
FROM restaurants r
WHERE u."Id" = r."ManagerId"
  AND u."Role" = 'Manager';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260510183000_RepairPendingUserActivationSchema', '10.0.7');

COMMIT;

START TRANSACTION;
ALTER TABLE audit_logs DROP CONSTRAINT "FK_audit_logs_tenants_TenantId";

ALTER TABLE audit_logs RENAME COLUMN "DeletedAt" TO "CreatedAt";

ALTER TABLE audit_logs RENAME COLUMN "DeletedData" TO "Detail";

ALTER TABLE audit_logs ADD "Action" character varying(32) NOT NULL DEFAULT 'Delete';

ALTER TABLE audit_logs ADD "ActorEmail" character varying(150);

ALTER TABLE audit_logs ADD "ActorRole" character varying(50);

ALTER TABLE audit_logs ADD "ActorUserId" integer;

ALTER TABLE audit_logs ADD "Target" character varying(200) NOT NULL DEFAULT '';

update audit_logs
set "Action" = 'Delete',
    "Target" = case
        when "RecordId" > 0 then "TableName" || ':' || "RecordId"::text
        else "TableName"
    end,
    "CreatedAt" = coalesce("CreatedAt", now())

ALTER TABLE audit_logs ALTER COLUMN "CreatedAt" SET NOT NULL;

CREATE INDEX idx_audit_logs_action ON audit_logs ("Action");

ALTER TABLE audit_logs ADD CONSTRAINT "FK_audit_logs_tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES tenants ("Id") ON DELETE SET NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260511113000_RefactorAuditLogsEventBased', '10.0.7');

COMMIT;

START TRANSACTION;
ALTER TABLE dining_sessions DROP CONSTRAINT "FK_dining_sessions_users_OpenedByUserId";

ALTER TABLE order_items DROP CONSTRAINT "FK_order_items_menu_items_MenuItemId";

ALTER TABLE purchase_orders DROP CONSTRAINT "FK_purchase_orders_suppliers_SupplierId";

ALTER TABLE restaurant_approval_requests DROP CONSTRAINT "FK_restaurant_approval_requests_users_RequestedByUserId";

ALTER TABLE table_sessions DROP CONSTRAINT "FK_table_sessions_users_OpenedByUserId";

ALTER TABLE dining_sessions ADD CONSTRAINT "FK_dining_sessions_users_OpenedByUserId" FOREIGN KEY ("OpenedByUserId") REFERENCES users ("Id") ON DELETE CASCADE;

ALTER TABLE order_items ADD CONSTRAINT "FK_order_items_menu_items_MenuItemId" FOREIGN KEY ("MenuItemId") REFERENCES menu_items ("Id") ON DELETE CASCADE;

ALTER TABLE purchase_orders ADD CONSTRAINT "FK_purchase_orders_suppliers_SupplierId" FOREIGN KEY ("SupplierId") REFERENCES suppliers ("Id") ON DELETE CASCADE;

ALTER TABLE restaurant_approval_requests ADD CONSTRAINT "FK_restaurant_approval_requests_users_RequestedByUserId" FOREIGN KEY ("RequestedByUserId") REFERENCES users ("Id") ON DELETE CASCADE;

ALTER TABLE table_sessions ADD CONSTRAINT "FK_table_sessions_users_OpenedByUserId" FOREIGN KEY ("OpenedByUserId") REFERENCES users ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260511123000_AllowConfiguredCascadeDeletes', '10.0.7');

COMMIT;

START TRANSACTION;
ALTER TABLE tables ADD "NeedsAssistance" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE tables ADD "RequestBill" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260513004819_AddTableServiceRequestFlags', '10.0.7');

COMMIT;

START TRANSACTION;
ALTER TABLE purchase_orders ADD "CreatedByEmail" character varying(320);

ALTER TABLE purchase_orders ADD "CreatedByUserId" integer;

ALTER TABLE purchase_orders ADD "InventoryItemId" integer;

ALTER TABLE purchase_orders ADD "ItemName" character varying(200);

ALTER TABLE purchase_orders ADD "Quantity" numeric(10,2);

ALTER TABLE purchase_orders ADD "UnitPrice" numeric(10,2);

CREATE INDEX idx_purchase_orders_created_by_user_id ON purchase_orders ("CreatedByUserId");

CREATE INDEX idx_purchase_orders_inventory_item_id ON purchase_orders ("InventoryItemId");

ALTER TABLE purchase_orders ADD CONSTRAINT "FK_purchase_orders_inventory_items_InventoryItemId" FOREIGN KEY ("InventoryItemId") REFERENCES inventory_items ("Id") ON DELETE SET NULL;

ALTER TABLE purchase_orders ADD CONSTRAINT "FK_purchase_orders_users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES users ("Id") ON DELETE SET NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260513192637_AddPurchaseOrderExportDetails', '10.0.7');

COMMIT;

