// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using srs.Server.Data;

#nullable disable

namespace srs.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260511123000_AllowConfiguredCascadeDeletes")]
    partial class AllowConfiguredCascadeDeletes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("srs.Server.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ActorEmail")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ActorRole")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("ActorUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("RecordId")
                        .HasColumnType("integer");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Action")
                        .HasDatabaseName("idx_audit_logs_action");

                    b.HasIndex("RecordId")
                        .HasDatabaseName("idx_audit_logs_record_id");

                    b.HasIndex("TableName")
                        .HasDatabaseName("idx_audit_logs_table_name");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_audit_logs_tenant_id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("srs.Server.Models.DiningSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OpenedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("PartySize")
                        .HasColumnType("integer");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SeatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TableId")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OpenedByUserId");

                    b.HasIndex("RestaurantId")
                        .HasDatabaseName("idx_dining_sessions_restaurant_id");

                    b.HasIndex("TableId")
                        .HasDatabaseName("idx_dining_sessions_table_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_dining_sessions_tenant_id");

                    b.HasIndex("TableId", "Status")
                        .HasDatabaseName("idx_dining_sessions_table_status");

                    b.ToTable("dining_sessions", null, t =>
                        {
                            t.HasCheckConstraint("CK_dining_sessions_party_size", "\"PartySize\" > 0");
                        });
                });

            modelBuilder.Entity("srs.Server.Models.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId")
                        .HasDatabaseName("idx_inventory_restaurant_id");

                    b.ToTable("inventory", (string)null);
                });

            modelBuilder.Entity("srs.Server.Models.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InventoryId")
                        .HasColumnType("integer");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId")
                        .HasDatabaseName("idx_inventory_items_inventory_id");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("idx_inventory_items_supplier_id");

                    b.ToTable("inventory_items", null, t =>
                        {
                            t.HasCheckConstraint("CK_inventory_items_quantity", "\"Quantity\" >= 0");

                            t.HasCheckConstraint("CK_inventory_items_unit_price", "\"UnitPrice\" >= 0");
                        });
                });

            modelBuilder.Entity("srs.Server.Models.KitchenQueue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("idx_kitchen_queue_order_id");

                    b.ToTable("kitchen_queue", (string)null);
                });

            modelBuilder.Entity("srs.Server.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CookingTime")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImagePublicId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("MenuId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("MenuId")
                        .HasDatabaseName("idx_menu_items_menu_id");

                    b.ToTable("menu_items", null, t =>
                        {
                            t.HasCheckConstraint("CK_menu_items_cooking_time", "\"CookingTime\" >= 0");

                            t.HasCheckConstraint("CK_menu_items_price", "\"Price\" >= 0");
                        });
                });

            modelBuilder.Entity("srs.Server.Models.MenuItemFilter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int?>("RestaurantId")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId")
                        .HasDatabaseName("idx_menu_item_filters_restaurant_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_menu_item_filters_tenant_id");

                    b.HasIndex("TenantId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("uq_menu_item_filters_tenant_slug");

                    b.ToTable("menu_item_filters", (string)null);
                });

            modelBuilder.Entity("srs.Server.Models.MenuItemFilterAssignment", b =>
                {
                    b.Property<int>("MenuItemId")
                        .HasColumnType("integer");

                    b.Property<int>("MenuItemFilterId")
                        .HasColumnType("integer");

                    b.HasKey("MenuItemId", "MenuItemFilterId");

                    b.HasIndex("MenuItemFilterId")
                        .HasDatabaseName("idx_menu_item_filter_assignments_filter_id");

                    b.ToTable("menu_item_filter_assignments", (string)null);
                });

            modelBuilder.Entity("srs.Server.Models.MenuOfRestaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId")
                        .HasDatabaseName("idx_menu_restaurant_id");

                    b.HasIndex("RestaurantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("uq_menu_restaurant_name");

                    b.ToTable("menu_of_restaurant", (string)null);
                });

            modelBuilder.Entity("srs.Server.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_notifications_user_id");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("srs.Server.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("DiningSessionId")
                        .HasColumnType("integer");

                    b.Property<int?>("PosUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TableId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int?>("WaiterStaffId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DiningSessionId")
                        .HasDatabaseName("idx_orders_dining_session_id");

                    b.HasIndex("PosUserId")
                        .HasDatabaseName("idx_orders_pos_user_id");

                    b.HasIndex("TableId")
                        .HasDatabaseName("idx_orders_table_id");

                    b.HasIndex("WaiterStaffId")
                        .HasDatabaseName("idx_orders_waiter_staff_id");

                    b.ToTable("orders", null, t =>
                        {
                            t.HasCheckConstraint("CK_orders_total", "\"Total\" >= 0");
                        });
                });

            modelBuilder.Entity("srs.Server.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId")
                        .HasDatabaseName("idx_order_items_menu_item_id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("idx_order_items_order_id");

                    b.ToTable("order_items", null, t =>
                        {
                            t.HasCheckConstraint("CK_order_items_price", "\"Price\" >= 0");

                            t.HasCheckConstraint("CK_order_items_quantity", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("srs.Server.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("idx_payments_order_id");

                    b.ToTable("payments", null, t =>
                        {
                            t.HasCheckConstraint("CK_payments_amount", "\"Amount\" >= 0");
                        });
                });

            modelBuilder.Entity("srs.Server.Models.PosWaiterSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OpenedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("PosUserId")
                        .HasColumnType("integer");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.Property<int>("StaffId")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PosUserId")
                        .HasDatabaseName("idx_pos_waiter_sessions_pos_user_id");

                    b.HasIndex("RestaurantId")
                        .HasDatabaseName("idx_pos_waiter_sessions_restaurant_id");

                    b.HasIndex("StaffId")
                        .HasDatabaseName("idx_pos_waiter_sessions_staff_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_pos_waiter_sessions_tenant_id");

                    b.ToTable("pos_waiter_sessions", (string)null);
                });

            modelBuilder.Entity("srs.Server.Models.PurchaseOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.Property<int>("SupplierId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("idx_purchase_orders_supplier_id");

                    b.ToTable("purchase_orders", null, t =>
                        {
                            t.HasCheckConstraint("CK_purchase_orders_total", "\"Total\" >= 0");
                        });
                });

            modelBuilder.Entity("srs.Server.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("srs.Server.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<DateOnly>("ReservationDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("ReservationTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TableId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TableId")
                        .HasDatabaseName("idx_reservations_table_id");

                    b.HasIndex("TableId", "ReservationDate", "ReservationTime")
                        .IsUnique()
                        .HasDatabaseName("uq_table_reservation_time");

                    b.ToTable("reservations", (string)null);
                });

            modelBuilder.Entity("srs.Server.Models.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CuisineType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_restaurants_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("uq_tenant_restaurant_name");

                    b.ToTable("restaurants", (string)null);
                });

            modelBuilder.Entity("srs.Server.Models.RestaurantApprovalRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminPasswordConfirmation")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProtectedPayload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("RequestedByUserId")
                        .HasColumnType("integer");

                    b.Property<int?>("RestaurantId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("TenantId");

                    b.ToTable("restaurant_approval_requests", (string)null);
                });

            modelBuilder.Entity("srs.Server.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId")
                        .HasDatabaseName("idx_reviews_restaurant_id");

                    b.HasIndex("UserId");

                    b.HasIndex("RestaurantId", "UserId")
                        .IsUnique();

                    b.ToTable("reviews", null, t =>
                        {
                            t.HasCheckConstraint("CK_reviews_rating", "\"Rating\" >= 1 AND \"Rating\" <= 5");
                        });
                });

            modelBuilder.Entity("srs.Server.Models.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StaffId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StaffId")
                        .HasDatabaseName("idx_shifts_staff_id");

                    b.ToTable("shifts", null, t =>
                        {
                            t.HasCheckConstraint("CK_shifts_time", "\"EndTime\" > \"StartTime\"");
                        });
                });

            modelBuilder.Entity("srs.Server.Models.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CredentialHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CredentialType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId")
                        .HasDatabaseName("idx_staff_restaurant_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_staff_tenant_id");

                    b.HasIndex("RestaurantId", "CredentialHash")
                        .IsUnique()
                        .HasDatabaseName("uq_staff_restaurant_credential");

                    b.ToTable("staff", (string)null);
                });

            modelBuilder.Entity("srs.Server.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contact")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId")
                        .HasDatabaseName("idx_suppliers_restaurant_id");

                    b.HasIndex("RestaurantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("uq_supplier_restaurant_name");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("srs.Server.Models.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedStaffId")
                        .HasColumnType("integer");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedStaffId");

                    b.HasIndex("RestaurantId")
                        .HasDatabaseName("idx_tables_restaurant_id");

                    b.HasIndex("RestaurantId", "Number")
                        .IsUnique()
                        .HasDatabaseName("uq_tables_restaurant_number");

                    b.ToTable("tables", null, t =>
                        {
                            t.HasCheckConstraint("CK_tables_capacity", "\"Capacity\" > 0");
                        });
                });

            modelBuilder.Entity("srs.Server.Models.TableSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("LastSeenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("OpenedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TableId")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OpenedByUserId");

                    b.HasIndex("RestaurantId")
                        .HasDatabaseName("idx_table_sessions_restaurant_id");

                    b.HasIndex("TableId")
                        .HasDatabaseName("idx_table_sessions_table_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_table_sessions_tenant_id");

                    b.HasIndex("TableId", "Status")
                        .HasDatabaseName("idx_table_sessions_table_status");

                    b.ToTable("table_sessions", (string)null);
                });

            modelBuilder.Entity("srs.Server.Models.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("srs.Server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActivated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int?>("RestaurantId")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("SupabaseUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("users_email_key");

                    b.HasIndex("RestaurantId")
                        .HasDatabaseName("idx_users_restaurant_id");

                    b.HasIndex("SupabaseUserId")
                        .IsUnique()
                        .HasDatabaseName("users_supabase_id_key");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_users_tenant_id");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("CK_users_role", "\"Role\" IN ('Pending','Owner','Manager','Admin','SuperAdmin','PosDevice','TableDevice','KitchenDevice','HostDevice')");
                        });
                });

            modelBuilder.Entity("srs.Server.Models.AuditLog", b =>
                {
                    b.HasOne("srs.Server.Models.Tenant", "Tenant")
                        .WithMany("AuditLogs")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("srs.Server.Models.DiningSession", b =>
                {
                    b.HasOne("srs.Server.Models.User", "OpenedByUser")
                        .WithMany()
                        .HasForeignKey("OpenedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("srs.Server.Models.Restaurant", "Restaurant")
                        .WithMany("DiningSessions")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("srs.Server.Models.Table", "Table")
                        .WithMany("DiningSessions")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("srs.Server.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OpenedByUser");

                    b.Navigation("Restaurant");

                    b.Navigation("Table");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("srs.Server.Models.Inventory", b =>
                {
                    b.HasOne("srs.Server.Models.Restaurant", "Restaurant")
                        .WithMany("Inventories")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("srs.Server.Models.InventoryItem", b =>
                {
                    b.HasOne("srs.Server.Models.Inventory", "Inventory")
                        .WithMany("InventoryItems")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("srs.Server.Models.Supplier", "Supplier")
                        .WithMany("InventoryItems")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Inventory");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("srs.Server.Models.KitchenQueue", b =>
                {
                    b.HasOne("srs.Server.Models.Order", "Order")
                        .WithMany("KitchenQueues")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("srs.Server.Models.MenuItem", b =>
                {
                    b.HasOne("srs.Server.Models.MenuOfRestaurant", "Menu")
                        .WithMany("MenuItems")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("srs.Server.Models.MenuItemFilter", b =>
                {
                    b.HasOne("srs.Server.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("srs.Server.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("srs.Server.Models.MenuItemFilterAssignment", b =>
                {
                    b.HasOne("srs.Server.Models.MenuItemFilter", "MenuItemFilter")
                        .WithMany("MenuItemAssignments")
                        .HasForeignKey("MenuItemFilterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("srs.Server.Models.MenuItem", "MenuItem")
                        .WithMany("FilterAssignments")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("MenuItemFilter");
                });

            modelBuilder.Entity("srs.Server.Models.MenuOfRestaurant", b =>
                {
                    b.HasOne("srs.Server.Models.Restaurant", "Restaurant")
                        .WithMany("MenuOfRestaurants")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("srs.Server.Models.Notification", b =>
                {
                    b.HasOne("srs.Server.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("srs.Server.Models.Order", b =>
                {
                    b.HasOne("srs.Server.Models.DiningSession", "DiningSession")
                        .WithMany("Orders")
                        .HasForeignKey("DiningSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("srs.Server.Models.User", "PosUser")
                        .WithMany("PosOrders")
                        .HasForeignKey("PosUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("srs.Server.Models.Table", "Table")
                        .WithMany("Orders")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("srs.Server.Models.Staff", "WaiterStaff")
                        .WithMany("Orders")
                        .HasForeignKey("WaiterStaffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DiningSession");

                    b.Navigation("PosUser");

                    b.Navigation("Table");

                    b.Navigation("WaiterStaff");
                });

            modelBuilder.Entity("srs.Server.Models.OrderItem", b =>
                {
                    b.HasOne("srs.Server.Models.MenuItem", "MenuItem")
                        .WithMany("OrderItems")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("srs.Server.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("srs.Server.Models.Payment", b =>
                {
                    b.HasOne("srs.Server.Models.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("srs.Server.Models.PosWaiterSession", b =>
                {
                    b.HasOne("srs.Server.Models.User", "PosUser")
                        .WithMany("PosWaiterSessions")
                        .HasForeignKey("PosUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("srs.Server.Models.Restaurant", "Restaurant")
                        .WithMany("PosWaiterSessions")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("srs.Server.Models.Staff", "Staff")
                        .WithMany("PosWaiterSessions")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("srs.Server.Models.Tenant", "Tenant")
                        .WithMany("PosWaiterSessions")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PosUser");

                    b.Navigation("Restaurant");

                    b.Navigation("Staff");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("srs.Server.Models.PurchaseOrder", b =>
                {
                    b.HasOne("srs.Server.Models.Restaurant", "Restaurant")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("srs.Server.Models.Supplier", "Supplier")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("srs.Server.Models.Report", b =>
                {
                    b.HasOne("srs.Server.Models.Restaurant", "Restaurant")
                        .WithMany("Reports")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("srs.Server.Models.Reservation", b =>
                {
                    b.HasOne("srs.Server.Models.Table", "Table")
                        .WithMany("Reservations")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Table");
                });

            modelBuilder.Entity("srs.Server.Models.Restaurant", b =>
                {
                    b.HasOne("srs.Server.Models.User", "Manager")
                        .WithMany("RestaurantManagers")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("srs.Server.Models.User", "Owner")
                        .WithMany("RestaurantOwners")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("srs.Server.Models.Tenant", "Tenant")
                        .WithMany("Restaurants")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");

                    b.Navigation("Owner");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("srs.Server.Models.RestaurantApprovalRequest", b =>
                {
                    b.HasOne("srs.Server.Models.User", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("srs.Server.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("srs.Server.Models.User", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("srs.Server.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestedByUser");

                    b.Navigation("Restaurant");

                    b.Navigation("ReviewedByUser");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("srs.Server.Models.Review", b =>
                {
                    b.HasOne("srs.Server.Models.Restaurant", "Restaurant")
                        .WithMany("Reviews")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("srs.Server.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("srs.Server.Models.Shift", b =>
                {
                    b.HasOne("srs.Server.Models.Staff", "Staff")
                        .WithMany("Shifts")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("srs.Server.Models.Staff", b =>
                {
                    b.HasOne("srs.Server.Models.Restaurant", "Restaurant")
                        .WithMany("Staff")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("srs.Server.Models.Tenant", "Tenant")
                        .WithMany("Staff")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("srs.Server.Models.Supplier", b =>
                {
                    b.HasOne("srs.Server.Models.Restaurant", "Restaurant")
                        .WithMany("Suppliers")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("srs.Server.Models.Table", b =>
                {
                    b.HasOne("srs.Server.Models.Staff", "AssignedStaff")
                        .WithMany("Tables")
                        .HasForeignKey("AssignedStaffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("srs.Server.Models.Restaurant", "Restaurant")
                        .WithMany("Tables")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedStaff");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("srs.Server.Models.TableSession", b =>
                {
                    b.HasOne("srs.Server.Models.User", "OpenedByUser")
                        .WithMany()
                        .HasForeignKey("OpenedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("srs.Server.Models.Restaurant", "Restaurant")
                        .WithMany("TableSessions")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("srs.Server.Models.Table", "Table")
                        .WithMany("TableSessions")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("srs.Server.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OpenedByUser");

                    b.Navigation("Restaurant");

                    b.Navigation("Table");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("srs.Server.Models.User", b =>
                {
                    b.HasOne("srs.Server.Models.Restaurant", "Restaurant")
                        .WithMany("DeviceUsers")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("srs.Server.Models.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Restaurant");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("srs.Server.Models.DiningSession", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("srs.Server.Models.Inventory", b =>
                {
                    b.Navigation("InventoryItems");
                });

            modelBuilder.Entity("srs.Server.Models.MenuItem", b =>
                {
                    b.Navigation("FilterAssignments");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("srs.Server.Models.MenuItemFilter", b =>
                {
                    b.Navigation("MenuItemAssignments");
                });

            modelBuilder.Entity("srs.Server.Models.MenuOfRestaurant", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("srs.Server.Models.Order", b =>
                {
                    b.Navigation("KitchenQueues");

                    b.Navigation("OrderItems");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("srs.Server.Models.Restaurant", b =>
                {
                    b.Navigation("DeviceUsers");

                    b.Navigation("DiningSessions");

                    b.Navigation("Inventories");

                    b.Navigation("MenuOfRestaurants");

                    b.Navigation("PosWaiterSessions");

                    b.Navigation("PurchaseOrders");

                    b.Navigation("Reports");

                    b.Navigation("Reviews");

                    b.Navigation("Staff");

                    b.Navigation("Suppliers");

                    b.Navigation("TableSessions");

                    b.Navigation("Tables");
                });

            modelBuilder.Entity("srs.Server.Models.Staff", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("PosWaiterSessions");

                    b.Navigation("Shifts");

                    b.Navigation("Tables");
                });

            modelBuilder.Entity("srs.Server.Models.Supplier", b =>
                {
                    b.Navigation("InventoryItems");

                    b.Navigation("PurchaseOrders");
                });

            modelBuilder.Entity("srs.Server.Models.Table", b =>
                {
                    b.Navigation("DiningSessions");

                    b.Navigation("Orders");

                    b.Navigation("Reservations");

                    b.Navigation("TableSessions");
                });

            modelBuilder.Entity("srs.Server.Models.Tenant", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("PosWaiterSessions");

                    b.Navigation("Restaurants");

                    b.Navigation("Staff");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("srs.Server.Models.User", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("PosOrders");

                    b.Navigation("PosWaiterSessions");

                    b.Navigation("RestaurantManagers");

                    b.Navigation("RestaurantOwners");
                });
#pragma warning restore 612, 618
        }
    }
}
